version: '3.8'

services:
  air-quality-dashboard:
    build: .
    image: webyhomelab/air-quality-dashboard:0.2
    container_name: air-quality-dashboard
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Kyiv
      - STATION_ID=13992
    volumes:
      - ./history.json:/app/history.json
